export const ALL_CARDS = [
  {
    cardImgFront: "./src/assets/typeicon1.png",
    cardImgBack: "./src/assets/typeicon1.png",
    cardTextFront: "What is this type?",
    cardTextBack: "Ghost",
    difficulty: "easy",
  },
  {
    cardImgFront: "./src/assets/typeicon2.png",
    cardImgBack: "./src/assets/typeicon2.png",
    cardTextFront: "What is this type?",
    cardTextBack: "Psychic",
    difficulty: "easy",
  },
  {
    cardImgFront: "./src/assets/typeicon3.png",
    cardImgBack: "./src/assets/typeicon3.png",
    cardTextFront: "What is this type?",
    cardTextBack: "Steel",
    difficulty: "easy",
  },
  {
    cardImgFront: "./src/assets/typeicon4.png",
    cardImgBack: "./src/assets/typeicon4.png",
    cardTextFront: "What is the resistance of this type?",
    cardTextBack: "Ice",
    difficulty: "medium",
  },
  {
    cardImgFront: "./src/assets/typeicon5.png",
    cardImgBack: "./src/assets/typeicon1.png",
    cardTextFront: "What is the resistance of this type?",
    cardTextBack: "Ghost",
    difficulty: "medium",
  },
  {
    cardImgFront: "./src/assets/typeicon6.png",
    cardImgBack: "./src/assets/resistance1.png",
    cardTextFront: "What is the resistance this type?",
    cardTextBack: "Fire, Electric, Water, Grass",
    difficulty: "medium",
  },
  {
    cardImgFront: "./src/assets/typeicon3.png",
    cardImgBack: "./src/assets/resistance2.png",
    cardTextFront: "What is the resistance this type?",
    cardTextBack: "Bug, Dragon, Fairy, Flying, Grass, Ice, Normal, Poison, Rock, Psychic",
    difficulty: "hard",
  },
  {
    cardImgFront: "./src/assets/dualtype1.png",
    cardImgBack: "./src/assets/resistance3.png",
    cardTextFront: "What is the resistance this dual-type?",
    cardTextBack: "Ghost, Normal, Poison, Bug, Fighting",
    difficulty: "hard",
  },
  {
    cardImgFront: "./src/assets/dualtype2.png",
    cardImgBack: "./src/assets/resistance4.png",
    cardTextFront: "What is the resistance this dual-type?",
    cardTextBack: "Ghost, Poison, Dark, Grass, Psychic",
    difficulty: "hard",
  },
];